server:
  port: 8107
spring:
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="8m48mpij" password="vAaRVki2l0t9wohPGJ5xTDBJIj3PJRWg";
 # redis:
 #   host: localhost
 #   port: 16379
    #    username: default
 #   password:
 #   timeout: 5000
  cloud:
    function:
      definition: updateAmountWalletBootcoin
    stream:
      bindings:
        updateAmountWalletBootcoin-in-0:
          destination: 8m48mpij-markettransaction-walletBootcoin

          
          
          
  data:
    mongodb:
      uri: mongodb+srv://erick:erickpinglo@cluster0.xdfgh.mongodb.net/bank